### ISSUE TITLE
Unnecessary zip files in dist directory

### ISSUE THREAD

**Issue by 2jun0** [yerofey/shortly-chrome#1]
Aren't [zip files](https://github.com/yerofey/shortly-chrome/tree/master/dist/_) already [released](https://github.com/yerofey/shortly-chrome/releases) in GitHub? I think it should be removed or listed in gitignore.

**Comment by yerofey** [comment]
Well, yeah, kinda
But this is dev repository, this isn't uploaded to the chrome webstore

**Comment by yerofey** [comment]
Can you, please, translate the description also?

```bash
Get the short URL just by clicking the extension logo

Features:
* Fast URL shortener
* QR code
```

**Comment by 2jun0** [comment]
Sure!

```
확장프로그램 로고 클릭으로 간소화된 URL을 가져올 수 있습니다.

기능:
* 빠른 URL 간소화
* QR 코드```

**Comment by yerofey** [comment]
Thank you!
